/*
 * TalesAPI
 *
 * This is the API of an app for learning English for Russian speakers
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ArrayOfLineNumbersInner : IEquatable<ArrayOfLineNumbersInner>
    { 
        /// <summary>
        /// Id of the Story to which the number&#x27;s line belongs
        /// </summary>
        /// <value>Id of the Story to which the number&#x27;s line belongs</value>
        [DataMember(Name="StoryId")]
        public string StoryId { get; set; }

        /// <summary>
        /// Id of the Line to which the number belongs
        /// </summary>
        /// <value>Id of the Line to which the number belongs</value>
        [DataMember(Name="LineId")]
        public string LineId { get; set; }

        /// <summary>
        /// The number of the line in the story
        /// </summary>
        /// <value>The number of the line in the story</value>
        [DataMember(Name="Number")]
        public decimal? Number { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArrayOfLineNumbersInner {\n");
            sb.Append("  StoryId: ").Append(StoryId).Append("\n");
            sb.Append("  LineId: ").Append(LineId).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ArrayOfLineNumbersInner)obj);
        }

        /// <summary>
        /// Returns true if ArrayOfLineNumbersInner instances are equal
        /// </summary>
        /// <param name="other">Instance of ArrayOfLineNumbersInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArrayOfLineNumbersInner other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    StoryId == other.StoryId ||
                    StoryId != null &&
                    StoryId.Equals(other.StoryId)
                ) && 
                (
                    LineId == other.LineId ||
                    LineId != null &&
                    LineId.Equals(other.LineId)
                ) && 
                (
                    Number == other.Number ||
                    Number != null &&
                    Number.Equals(other.Number)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (StoryId != null)
                    hashCode = hashCode * 59 + StoryId.GetHashCode();
                    if (LineId != null)
                    hashCode = hashCode * 59 + LineId.GetHashCode();
                    if (Number != null)
                    hashCode = hashCode * 59 + Number.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ArrayOfLineNumbersInner left, ArrayOfLineNumbersInner right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ArrayOfLineNumbersInner left, ArrayOfLineNumbersInner right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
