/*
 * Lines Collection
 *
 * Endpoints for updating Lines of Tales App
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Line : IEquatable<Line>
    { 
        /// <summary>
        /// ID of the Line
        /// </summary>
        /// <value>ID of the Line</value>
        [DataMember(Name="LineId")]
        public string LineId { get; set; }

        /// <summary>
        /// The line that a character says
        /// </summary>
        /// <value>The line that a character says</value>
        [DataMember(Name="LineContent")]
        public string LineContent { get; set; }

        /// <summary>
        /// Character that says the line
        /// </summary>
        /// <value>Character that says the line</value>
        [DataMember(Name="CharacterId")]
        public string CharacterId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Line {\n");
            sb.Append("  LineId: ").Append(LineId).Append("\n");
            sb.Append("  LineContent: ").Append(LineContent).Append("\n");
            sb.Append("  CharacterId: ").Append(CharacterId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Line)obj);
        }

        /// <summary>
        /// Returns true if Line instances are equal
        /// </summary>
        /// <param name="other">Instance of Line to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Line other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LineId == other.LineId ||
                    LineId != null &&
                    LineId.Equals(other.LineId)
                ) && 
                (
                    LineContent == other.LineContent ||
                    LineContent != null &&
                    LineContent.Equals(other.LineContent)
                ) && 
                (
                    CharacterId == other.CharacterId ||
                    CharacterId != null &&
                    CharacterId.Equals(other.CharacterId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (LineId != null)
                    hashCode = hashCode * 59 + LineId.GetHashCode();
                    if (LineContent != null)
                    hashCode = hashCode * 59 + LineContent.GetHashCode();
                    if (CharacterId != null)
                    hashCode = hashCode * 59 + CharacterId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Line left, Line right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Line left, Line right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
