/*
 * TalesAPI
 *
 * This is the API of an app for learning English for Russian speakers
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpGet]
        [Route("/api/Character/41f1a391-26ee-4dd2-0f60-08d80a57e28d")]
        [ValidateModelState]
        [SwaggerOperation("ApiCharacter41f1a39126ee4dd20f6008d80a57e28dGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiCharacter41f1a39126ee4dd20f6008d80a57e28dGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpDelete]
        [Route("/api/Character")]
        [ValidateModelState]
        [SwaggerOperation("ApiCharacterDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiCharacterDelete()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="body"></param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpPost]
        [Route("/api/Character")]
        [ValidateModelState]
        [SwaggerOperation("ApiCharacterPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiCharacterPost([FromBody]Object body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="body"></param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpPut]
        [Route("/api/Character")]
        [ValidateModelState]
        [SwaggerOperation("ApiCharacterPut")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiCharacterPut([FromBody]Object body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpDelete]
        [Route("/api/Line")]
        [ValidateModelState]
        [SwaggerOperation("ApiLineDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiLineDelete()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="lineId">A GUID id of the line</param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpGet]
        [Route("/api/Line")]
        [ValidateModelState]
        [SwaggerOperation("ApiLineGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiLineGet([FromRoute][Required]string lineId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="body">Provide an array of Line Numbers to create</param>
        /// <response code="200">The Line Numbers were successfully deleted</response>
        /// <response code="400">Bad Request</response>
        /// <response code="403">Access Denied</response>
        /// <response code="404">The resource is not found</response>
        [HttpDelete]
        [Route("/api/LineNumber")]
        [ValidateModelState]
        [SwaggerOperation("ApiLineNumberDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(ArrayOfLineNumbers), description: "The Line Numbers were successfully deleted")]
        public virtual IActionResult ApiLineNumberDelete([FromBody]List<string> body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ArrayOfLineNumbers));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ {\n  \"StoryId\" : \"f89da017-05bb-48b0-c02f-08d80a57a67b\",\n  \"LineId\" : \"e520e6df-4ac0-49c8-7dcd-08d80a569eba\",\n  \"Number\" : 1\n}, {\n  \"StoryId\" : \"a58da017-05bb-48b0-c02f-08d80a57s458\",\n  \"LineId\" : \"d589e6df-4ac0-49c8-7dcd-08d80a548lfg\",\n  \"Number\" : 2\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<ArrayOfLineNumbers>(exampleJson)
                        : default(ArrayOfLineNumbers);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Delete all Line Numbers of a Story</remarks>
        /// <param name="id">An ID to look up one or more values</param>
        /// <response code="200">All Story Line Numbers were deleted</response>
        [HttpDelete]
        [Route("/api/LineNumber/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ApiLineNumberIdDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "All Story Line Numbers were deleted")]
        public virtual IActionResult ApiLineNumberIdDelete([FromRoute][Required]string id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get Line by its Id</remarks>
        /// <param name="id">An ID to look up one or more values</param>
        /// <response code="200">The Line Numbers were successfully deleted</response>
        /// <response code="400">Bad Request</response>
        /// <response code="403">Access Denied</response>
        /// <response code="404">The resource is not found</response>
        [HttpGet]
        [Route("/api/LineNumber/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ApiLineNumberIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(ArrayOfLineNumbers), description: "The Line Numbers were successfully deleted")]
        public virtual IActionResult ApiLineNumberIdGet([FromRoute][Required]string id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ArrayOfLineNumbers));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ {\n  \"StoryId\" : \"f89da017-05bb-48b0-c02f-08d80a57a67b\",\n  \"LineId\" : \"e520e6df-4ac0-49c8-7dcd-08d80a569eba\",\n  \"Number\" : 1\n}, {\n  \"StoryId\" : \"a58da017-05bb-48b0-c02f-08d80a57s458\",\n  \"LineId\" : \"d589e6df-4ac0-49c8-7dcd-08d80a548lfg\",\n  \"Number\" : 2\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<ArrayOfLineNumbers>(exampleJson)
                        : default(ArrayOfLineNumbers);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Add new Line Numbers</remarks>
        /// <param name="body">Provide an array of Line Numbers to create</param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        /// <response code="400">Bad Request</response>
        /// <response code="403">Access Denied</response>
        /// <response code="404">The resource is not found</response>
        [HttpPost]
        [Route("/api/LineNumber")]
        [ValidateModelState]
        [SwaggerOperation("ApiLineNumberPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(ArrayOfLineNumbers), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiLineNumberPost([FromBody]List<string> body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ArrayOfLineNumbers));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ {\n  \"StoryId\" : \"f89da017-05bb-48b0-c02f-08d80a57a67b\",\n  \"LineId\" : \"e520e6df-4ac0-49c8-7dcd-08d80a569eba\",\n  \"Number\" : 1\n}, {\n  \"StoryId\" : \"a58da017-05bb-48b0-c02f-08d80a57s458\",\n  \"LineId\" : \"d589e6df-4ac0-49c8-7dcd-08d80a548lfg\",\n  \"Number\" : 2\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<ArrayOfLineNumbers>(exampleJson)
                        : default(ArrayOfLineNumbers);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Update Line Numbers of a Line to describe in what sequence they need to be in the story</remarks>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad Request</response>
        /// <response code="403">Access Denied</response>
        /// <response code="404">The resource is not found</response>
        [HttpPut]
        [Route("/api/LineNumber")]
        [ValidateModelState]
        [SwaggerOperation("ApiLineNumberPut")]
        [SwaggerResponse(statusCode: 200, type: typeof(ArrayOfLineNumbers), description: "OK")]
        public virtual IActionResult ApiLineNumberPut([FromBody]List<ArrayOfLineNumbersInner> body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ArrayOfLineNumbers));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ {\n  \"StoryId\" : \"f89da017-05bb-48b0-c02f-08d80a57a67b\",\n  \"LineId\" : \"e520e6df-4ac0-49c8-7dcd-08d80a569eba\",\n  \"Number\" : 1\n}, {\n  \"StoryId\" : \"a58da017-05bb-48b0-c02f-08d80a57s458\",\n  \"LineId\" : \"d589e6df-4ac0-49c8-7dcd-08d80a548lfg\",\n  \"Number\" : 2\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<ArrayOfLineNumbers>(exampleJson)
                        : default(ArrayOfLineNumbers);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="body"></param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpPost]
        [Route("/api/Line")]
        [ValidateModelState]
        [SwaggerOperation("ApiLinePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiLinePost([FromBody]Object body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="body"></param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpPut]
        [Route("/api/Line")]
        [ValidateModelState]
        [SwaggerOperation("ApiLinePut")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiLinePut([FromBody]Object body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="storyId">A Guid Story Id</param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpDelete]
        [Route("/api/Story")]
        [ValidateModelState]
        [SwaggerOperation("ApiStoryDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiStoryDelete([FromRoute][Required]string storyId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get a story By its id</remarks>
        /// <param name="storyId">A Guid Id of a Story</param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpGet]
        [Route("/api/Story")]
        [ValidateModelState]
        [SwaggerOperation("ApiStoryGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiStoryGet([FromRoute][Required]string storyId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Allows to get Story Information by ID</remarks>
        /// <param name="storyId">A Guid Story Id</param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpGet]
        [Route("/api/Story/GetStoryById/{StoryId}")]
        [ValidateModelState]
        [SwaggerOperation("ApiStoryGetStoryByIdStoryIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiStoryGetStoryByIdStoryIdGet([FromRoute][Required]string storyId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="body"></param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpPost]
        [Route("/api/Story")]
        [ValidateModelState]
        [SwaggerOperation("ApiStoryPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiStoryPost([FromBody]Body1 body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Auto generated using Swagger Inspector</remarks>
        /// <param name="body"></param>
        /// <response code="200">Auto generated using Swagger Inspector</response>
        [HttpPut]
        [Route("/api/Story")]
        [ValidateModelState]
        [SwaggerOperation("ApiStoryPut")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Auto generated using Swagger Inspector")]
        public virtual IActionResult ApiStoryPut([FromBody]Body body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
